#include <gmock/gmock.h>
#include <gtest/gtest.h>

#include "FreeRTOS.h"
#include "freertos_config.hpp"

TEST(FreertosConfigTest, HasMutex) {
#if configUSE_MUTEXES == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_MUTEX, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_MUTEX, 0);
#endif
}

TEST(FreertosConfigTest, HasCountingSemaphore) {
#if defined(configUSE_COUNTING_SEMAPHORES) && configUSE_COUNTING_SEMAPHORES == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE, 0);
#endif
}

TEST(FreertosConfigTest, HasRecursiveMutex) {
#if defined(configUSE_RECURSIVE_MUTEXES) && configUSE_RECURSIVE_MUTEXES == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX, 0);
#endif
}

TEST(FreertosConfigTest, HasSwTimer) {
#if configUSE_TIMERS == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER, 0);
#endif
}

TEST(FreertosConfigTest, HasTaskNotifications) {
#if configUSE_TASK_NOTIFICATIONS == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS, 0);
#endif
}

TEST(FreertosConfigTest, HasStreamBuffer) {
#if defined(configUSE_STREAM_BUFFERS) && configUSE_STREAM_BUFFERS == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER, 0);
#endif
}

TEST(FreertosConfigTest, HasEventGroup) {
#if defined(configUSE_EVENT_GROUPS) && configUSE_EVENT_GROUPS == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP, 0);
#endif
}

TEST(FreertosConfigTest, HasStaticAllocation) {
#if configSUPPORT_STATIC_ALLOCATION == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION, 0);
#endif
}

TEST(FreertosConfigTest, HasDynamicAllocation) {
#if configSUPPORT_DYNAMIC_ALLOCATION == 1
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION, 0);
#endif
}

TEST(FreertosConfigTest, Cpp17Detected) {
#if __cplusplus >= 201703L
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP17, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP17, 0);
#endif
}

TEST(FreertosConfigTest, Cpp20Detected) {
#if __cplusplus >= 202002L
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP20, 1);
#else
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP20, 0);
#endif
}

TEST(FreertosConfigTest, Cpp17ImpliesCpp20isZeroWhenNotCpp20) {
#if __cplusplus >= 202002L
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP20, 1);
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP17, 1);
#elif __cplusplus >= 201703L
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP17, 1);
  EXPECT_EQ(FREERTOS_CPP_WRAPPERS_CPP20, 0);
#endif
}

TEST(FreertosConfigTest, FeatureMacrosAreZeroOrOne) {
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_MUTEX == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_MUTEX == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION == 1);
  EXPECT_TRUE(FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION == 0 ||
              FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION == 1);
}