#!/usr/bin/env python3
"""Generate freertos_cpp_wrappers_config.hpp from Kconfig.

This script uses kconfiglib to process the Kconfig file and generate
the C++ configuration header. It can be used standalone without CMake.

Usage:
    python3 scripts/gen_config.py [--kconfig KCONFIG] [--output OUTPUT]

With no arguments, it reads Kconfig from the project root and writes
to include/freertos_cpp_wrappers_config.hpp.

Requires: kconfiglib (pip install kconfiglib)
"""

import argparse
import os
import sys


def generate_config_header(config, output_path):
    """Generate the C++ config header from a Kconfig Config object."""
    lines = [
        "/**********************************************************************************",
        "@file freertos_cpp_wrappers_config.hpp",
        "@author Auto-generated by gen_config.py",
        "@brief Kconfig-generated configuration header for FreeRTOS C++ Wrappers",
        "@version 3.1.0",
        "",
        "This file was auto-generated from Kconfig by scripts/gen_config.py.",
        "Do not edit manually. Edit Kconfig and re-run gen_config.py instead.",
        "**********************************************************************************/",
        "",
        "#pragma once",
        "",
        '#ifndef __cplusplus',
        '#error "This header is for C++ only"',
        "#endif",
        "",
    ]

    bool_options = [
        ("FREERTOS_CPP_WRAPPERS_ENABLE_GTHR_BACKEND",
         "Phase 3 -- Standard Library Integration Backends"),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_THREADING", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_ATOMIC_WAIT_NOTIFY",
         "Atomic Wait/Notify"),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_STD_THREAD",
         "C++ Standard Library Features"),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_STD_MUTEX", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_STD_SHARED_MUTEX", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_STD_FUTURE", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_EXPECTED",
         "Library Feature Toggles"),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_SPAN", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_THREAD_SAFETY", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_CONCEPTS", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_ALLOCATOR", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_ISR_RESULT", None),
        ("FREERTOS_CPP_WRAPPERS_ENABLE_STRONG_TYPES", None),
    ]

    int_options = [
        ("FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_IMPL", None),
        ("FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_TABLE_SIZE", None),
        ("FREERTOS_CPP_WRAPPERS_ALLOC_STRATEGY",
         "Allocation Strategy / Condition Variable"),
        ("FREERTOS_CPP_WRAPPERS_CONDVAR_IMPL", None),
    ]

    section_printed = set()

    for name, section in bool_options:
        if section and section not in section_printed:
            lines.append(
                "/* ========================================================================="
                " */"
            )
            lines.append(f"/* {section}")
            lines.append(
                "                                                 "
                "                          */"
            )
            lines.append(
                "/* ========================================================================="
                " */"
            )
            lines.append("")
            section_printed.add(section)

        val = config.get(name, 0)
        if isinstance(val, bool):
            val = 1 if val else 0
        lines.append(f"#ifndef {name}")
        lines.append(f"#define {name} {val}")
        lines.append(f"#endif")
        lines.append("")

    for name, section in int_options:
        if section and section not in section_printed:
            lines.append(
                "/* ========================================================================="
                " */"
            )
            lines.append(f"/* {section}")
            lines.append(
                "                                                 "
                "                          */"
            )
            lines.append(
                "/* ========================================================================="
                " */"
            )
            lines.append("")
            section_printed.add(section)

        val = config.get(name, 0)
        lines.append(f"#ifndef {name}")
        lines.append(f"#define {name} {val}")
        lines.append(f"#endif")
        lines.append("")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate config header from Kconfig"
    )
    parser.add_argument(
        "--kconfig",
        default=None,
        help="Path to Kconfig file (default: Kconfig in project root)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output header file path "
             "(default: include/freertos_cpp_wrappers_config.hpp)",
    )
    parser.add_argument(
        "--config-file",
        default=".config",
        help="Path to .config file (default: .config)",
    )
    args = parser.parse_args()

    try:
        from kconfiglib import Kconfig
    except ImportError:
        print(
            "Error: kconfiglib is required. Install it with: "
            "pip install kconfiglib",
            file=sys.stderr,
        )
        sys.exit(1)

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    kconfig_path = args.kconfig or os.path.join(project_root, "Kconfig")
    output_path = args.output or os.path.join(
        project_root, "include", "freertos_cpp_wrappers_config.hpp"
    )

    kconf = Kconfig(kconfig_path)
    config_file = os.path.join(project_root, args.config_file)

    if os.path.exists(config_file):
        kconf.load_config(config_file)
    else:
        print(
            f"No .config file found at {config_file}, "
            f"using Kconfig defaults"
        )

    config = {}
    for sym in kconf.unique_defined_syms:
        if sym.str_value == "y":
            config[sym.name] = True
        elif sym.str_value == "n":
            config[sym.name] = False
        else:
            try:
                config[sym.name] = int(sym.str_value)
            except ValueError:
                config[sym.name] = sym.str_value

    generate_config_header(config, output_path)


if __name__ == "__main__":
    main()