/**********************************************************************************
@file freertos_config.hpp
@author Andrey V. Shchekin <aschokin@gmail.com>
@brief Feature detection header for FreeRTOS C++ Wrappers
@version 3.1.0
@date 2026-04-21

The MIT License (MIT)

FreeRTOS C++ Wrappers Library
https://github.com/aschokinatgmail/freertos_cpp_wrappers/

Copyright(c) 2024 Andrey V. Shchekin <aschokin@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do
 so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
************************************************************************************/

/** @file freertos_config.hpp
 *  @brief Feature detection header for FreeRTOS C++ Wrappers.
 *
 *  Defines compile-time feature macros based on FreeRTOS configuration
 *  (FreeRTOSConfig.h), the C++ standard in use, and the Kconfig-based
 *  library configuration (freertos_cpp_wrappers_config.hpp).
 *
 *  When built with CMake, the configuration header is auto-generated from
 *  include/freertos_cpp_wrappers_config.hpp.in. When used header-only
 *  without CMake, sensible defaults are provided.
 *
 *  Key macros (from FreeRTOS config):
 *  - FREERTOS_CPP_WRAPPERS_CPP17 / FREERTOS_CPP_WRAPPERS_CPP20: C++ standard detection
 *  - FREERTOS_CPP_WRAPPERS_HAS_MUTEX: configUSE_MUTEXES
 *  - FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE: configUSE_COUNTING_SEMAPHORES
 *  - FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX: configUSE_RECURSIVE_MUTEXES
 *  - FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER: configUSE_TIMERS
 *  - FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS: configUSE_TASK_NOTIFICATIONS
 *  - FREERTOS_CPP_WRAPPERS_HAS_INDEXED_NOTIFICATIONS: configTASK_NOTIFICATION_ARRAY_ENTRIES > 1
 *  - FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER: configUSE_STREAM_BUFFERS
 *  - FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP: configUSE_EVENT_GROUPS
 *  - FREERTOS_CPP_WRAPPERS_HAS_QUEUE_SET: configUSE_QUEUE_SETS
 *  - FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION: configSUPPORT_STATIC_ALLOCATION
 *  - FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION: configSUPPORT_DYNAMIC_ALLOCATION
 *  - FREERTOS_CPP_WRAPPERS_HAS_SMP_AFFINITY: configNUMBER_OF_CORES > 1 && configUSE_CORE_AFFINITY
 *  - FREERTOS_CPP_WRAPPERS_HAS_THREAD_SAFETY_ANNOTATIONS: opt-in via FREERTOS_CPP_WRAPPERS_THREAD_SAFETY_ANNOTATIONS
 *
 *  Key macros (from Kconfig configuration):
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_GTHR_BACKEND
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_THREADING
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_ATOMIC_WAIT_NOTIFY
 *  - FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_IMPL
 *  - FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_TABLE_SIZE
 *  - FREERTOS_CPP_WRAPPERS_ALLOC_STRATEGY
 *  - FREERTOS_CPP_WRAPPERS_CONDVAR_IMPL
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_STD_THREAD
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_STD_MUTEX
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_STD_SHARED_MUTEX
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_STD_FUTURE
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_EXPECTED
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_SPAN
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_THREAD_SAFETY
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_CONCEPTS
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_ALLOCATOR
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_ISR_RESULT
 *  - FREERTOS_CPP_WRAPPERS_ENABLE_STRONG_TYPES
 */

#pragma once

#if __has_include("freertos_cpp_wrappers_config.hpp")
#include "freertos_cpp_wrappers_config.hpp"
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_GTHR_BACKEND
#define FREERTOS_CPP_WRAPPERS_ENABLE_GTHR_BACKEND 0
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_THREADING
#define FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_THREADING 0
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_ATOMIC_WAIT_NOTIFY
#define FREERTOS_CPP_WRAPPERS_ENABLE_ATOMIC_WAIT_NOTIFY 0
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_IMPL
#define FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_IMPL 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_TABLE_SIZE
#define FREERTOS_CPP_WRAPPERS_ATOMIC_WAIT_TABLE_SIZE 16
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ALLOC_STRATEGY
#define FREERTOS_CPP_WRAPPERS_ALLOC_STRATEGY 3
#endif

#ifndef FREERTOS_CPP_WRAPPERS_CONDVAR_IMPL
#define FREERTOS_CPP_WRAPPERS_CONDVAR_IMPL 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_STD_THREAD
#define FREERTOS_CPP_WRAPPERS_ENABLE_STD_THREAD 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_STD_MUTEX
#define FREERTOS_CPP_WRAPPERS_ENABLE_STD_MUTEX 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_STD_SHARED_MUTEX
#define FREERTOS_CPP_WRAPPERS_ENABLE_STD_SHARED_MUTEX 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_STD_FUTURE
#define FREERTOS_CPP_WRAPPERS_ENABLE_STD_FUTURE 0
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_EXPECTED
#define FREERTOS_CPP_WRAPPERS_ENABLE_EXPECTED 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_SPAN
#define FREERTOS_CPP_WRAPPERS_ENABLE_SPAN 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_THREAD_SAFETY
#define FREERTOS_CPP_WRAPPERS_ENABLE_THREAD_SAFETY 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_CONCEPTS
#define FREERTOS_CPP_WRAPPERS_ENABLE_CONCEPTS 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_ALLOCATOR
#define FREERTOS_CPP_WRAPPERS_ENABLE_EXTERNAL_ALLOCATOR 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_ISR_RESULT
#define FREERTOS_CPP_WRAPPERS_ENABLE_ISR_RESULT 1
#endif

#ifndef FREERTOS_CPP_WRAPPERS_ENABLE_STRONG_TYPES
#define FREERTOS_CPP_WRAPPERS_ENABLE_STRONG_TYPES 1
#endif

#include <FreeRTOS.h>

#if __cplusplus >= 202002L
#define FREERTOS_CPP_WRAPPERS_CPP20 1
#define FREERTOS_CPP_WRAPPERS_CPP17 1
#elif __cplusplus >= 201703L
#define FREERTOS_CPP_WRAPPERS_CPP17 1
#define FREERTOS_CPP_WRAPPERS_CPP20 0
#else
#define FREERTOS_CPP_WRAPPERS_CPP17 0
#define FREERTOS_CPP_WRAPPERS_CPP20 0
#endif

#if defined(configUSE_MUTEXES) && configUSE_MUTEXES == 1
#define FREERTOS_CPP_WRAPPERS_HAS_MUTEX 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_MUTEX 0
#endif

#if defined(configUSE_COUNTING_SEMAPHORES) && configUSE_COUNTING_SEMAPHORES == 1
#define FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_COUNTING_SEMAPHORE 0
#endif

#if defined(configUSE_RECURSIVE_MUTEXES) && configUSE_RECURSIVE_MUTEXES == 1
#define FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX 0
#endif

#if defined(configUSE_TIMERS) && configUSE_TIMERS == 1
#define FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_SW_TIMER 0
#endif

#if defined(configUSE_TASK_NOTIFICATIONS) && configUSE_TASK_NOTIFICATIONS == 1
#define FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_TASK_NOTIFICATIONS 0
#endif

#if defined(configTASK_NOTIFICATION_ARRAY_ENTRIES) &&                          \
    configTASK_NOTIFICATION_ARRAY_ENTRIES > 1
#define FREERTOS_CPP_WRAPPERS_HAS_INDEXED_NOTIFICATIONS 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_INDEXED_NOTIFICATIONS 0
#endif

#if defined(configUSE_STREAM_BUFFERS) && configUSE_STREAM_BUFFERS == 1
#define FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_STREAM_BUFFER 0
#endif

#if defined(configUSE_EVENT_GROUPS) && configUSE_EVENT_GROUPS == 1
#define FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_EVENT_GROUP 0
#endif

#if defined(configUSE_QUEUE_SETS) && configUSE_QUEUE_SETS == 1
#define FREERTOS_CPP_WRAPPERS_HAS_QUEUE_SET 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_QUEUE_SET 0
#endif

#if defined(configSUPPORT_STATIC_ALLOCATION) &&                                \
    configSUPPORT_STATIC_ALLOCATION == 1
#define FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION 0
#endif

#if defined(configSUPPORT_DYNAMIC_ALLOCATION) &&                               \
    configSUPPORT_DYNAMIC_ALLOCATION == 1
#define FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION 0
#endif

#if FREERTOS_CPP_WRAPPERS_HAS_RECURSIVE_MUTEX &&                               \
    !FREERTOS_CPP_WRAPPERS_HAS_MUTEX
#error "configUSE_RECURSIVE_MUTEXES requires configUSE_MUTEXES to be enabled"
#endif

#if !FREERTOS_CPP_WRAPPERS_HAS_STATIC_ALLOCATION &&                            \
    !FREERTOS_CPP_WRAPPERS_HAS_DYNAMIC_ALLOCATION
#error "At least one of configSUPPORT_STATIC_ALLOCATION or "                   \
       "configSUPPORT_DYNAMIC_ALLOCATION must be enabled"
#endif

#if defined(configNUMBER_OF_CORES) && configNUMBER_OF_CORES > 1 &&             \
    defined(configUSE_CORE_AFFINITY) && configUSE_CORE_AFFINITY == 1
#define FREERTOS_CPP_WRAPPERS_HAS_SMP_AFFINITY 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_SMP_AFFINITY 0
#endif

#if defined(configUSE_TICKLESS_IDLE) && configUSE_TICKLESS_IDLE != 0
#define FREERTOS_CPP_WRAPPERS_HAS_TICKLESS_IDLE 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_TICKLESS_IDLE 0
#endif

#if !FREERTOS_CPP_WRAPPERS_CPP17
#error "FreeRTOS C++ Wrappers require C++17 or later"
#endif

#if defined(FREERTOS_CPP_WRAPPERS_THREAD_SAFETY_ANNOTATIONS) &&                \
    FREERTOS_CPP_WRAPPERS_THREAD_SAFETY_ANNOTATIONS
#define FREERTOS_CPP_WRAPPERS_HAS_THREAD_SAFETY_ANNOTATIONS 1
#else
#define FREERTOS_CPP_WRAPPERS_HAS_THREAD_SAFETY_ANNOTATIONS 0
#endif